/usr/share/rebost/gui/rebostGui.py flags=(attach_disconnected) {
  include <abstractions/base>
  capability dac_read_search,
  capability sys_resource,
  capability setgid,
  capability audit_write,
  capability chown,
  capability fowner,
  capability dac_override,
  capability kill,
  capability setuid,
  capability fsetid,
  capability sys_nice,
  capability sys_ptrace,
  ptrace peer=unconfined,
  ptrace peer=/usr/sbin/cups-browsed,
  ptrace peer=snap.cups.cups-browsed,
  ptrace peer=snap.cups.cupsd,
  /dev/tty rw,
  /dev/pts/* wr,
  /dev/ptmx wr,
  /etc/apport/blacklist.d/{,*} mr,
  /etc/apt/apt.conf.d/ mr,
  /etc/apt/apt.conf.d/{,**/}* cixwmrkl,
  /etc/apt/sources.list.d/{,**/}* cxrwlk,
  /etc/apt/trusted.gpg.d/{,**/}* cxrwlk,
  /etc/bash.bashrc r,
  /etc/default/locale r,
  /etc/dpkg/{,**/}* r,
  /etc/{,**/}* mr,
  /etc/epi.token cxrw,
  /etc/fonts/{,**/}* r,
  /etc/gtk-3.0/{,**/}* r,
  /etc/pam.d/{,**/}* r,
  /etc/n4d/key r,
  /etc/security/{,**/}* r,
  /etc/ssl/certs/ca-certificates.crt r,
  /etc/ssl/openssl.cnf rw,
  /etc/xdg/{,**/}* r,
  /proc/ r,
  /proc/*/attr/{,**/}* r,
  /proc/@{pid}/{,**/}* cxrwlkm,
  /proc/sys/kernel/random/boot_id r,
  /proc/sys/kernel/seccomp/actions_avail r,
  /proc/cgroups mr,
  /proc/locks mr,
  /proc/cmdline mr,
  /proc/sys/kernel/osrelease r,
  /proc/uptime r,
  /proc/sys/kernel/pid_max r,
  /run/dbus/system_bus_socket rw,
  /run/user/**/bus rw,
  /run/nscd/socket wr,
  /run/snapd.socket wr,
  /run/nslcd/socket wr,
  /run/dbus/system_bus_socket wr,
  /run/systemd/resolve/stub-resolv.conf r,
  /run/utmp rk,
  /tmp/rebost/{,**/}* cixrw,
  /tmp/{,**/}* cixrwlkm,
  /{,usr/}bin/sh cixrw,
  /usr/bin/{,**/}* cixrmw,
  /usr/bin/apt px -> unsecuredpkg,
  /usr/bin/apt-cache px -> unsecuredpkg,
  /usr/bin/apt-config px -> unsecuredpkg,
  /usr/bin/apt-get px -> unsecuredpkg,
  /usr/bin/dpkg px -> unsecuredpkg,
  /usr/bin/flatpak px -> unsecureflatpak,
  /usr/bin/pkcon px -> unsecuredpkcon,
  /usr/bin/snap px -> unsecuresnap,
  /usr/lib{,**/}* mrix,
  /usr/{,local/}lib/python3*/dist-packages/{,**} mr,
  /usr/sbin/ r,
  /usr/sbin/epi-gtk cixrw,
  /usr/sbin/sendmail cixrw,
  /usr/share/fonts/{,**/}* rcixl,
  /usr/share/rebost-data/{,**/}* r,
  /usr/share/rebost/{,**/}* cixrmkw,
  /usr/share/zero-center/{,**/}* cixrmkw,
  /usr/share/*/*_script cixrm,
  /usr/{,local/}share/{,**/}* r,
  / r,
  /var/cache/{,**/}* rwklm,
  /var/lib/app-info/{,**/}* r,
  /var/lib/apt/{,**/}* r,
  /var/lib/apt/lists/{,**/}* rwk,
  /var/lib/dpkg/{,**/}* r,
  /var/lib/dpkg/lock* cxrwk,
  /var/lib/flatpak/{,**/}* r,
  /var/tmp/{,**/}* cixrwk,
  @{HOME}/{,**/}* rwkix,
  @{HOME}/.Xauthority r,
  network,
  dbus,
  }
