profile /usr/share/zero-center/zero-center.py {
  include <abstractions/base>
  capability setgid,
  capability audit_write,
  capability chown,
  capability fowner,
  capability dac_read_search,
  capability dac_override,
  capability kill,
  capability setuid,
  capability setpcap,
  capability fsetid,
  capability sys_nice,
  capability sys_admin,
  capability net_admin,
  capability sys_ptrace,
  audit ptrace (trace) peer=@{profile_name},
  audit ptrace peer=@{profile_name},
  dbus,
  network,
  /{,usr/}bin/{,**/}* rwix,
  /dev/pts/{,**/}* wr,
  /dev/ptmx wr,
  /dev/tty wr,
  /etc/{,**/}* r,
  /etc/epi.token rwlk,
  /opt/{,**/}* r,
  /proc/{,**/}* r,
  /run/{,**/}* rk,
  /run/dbus/system_bus_socket rw,
  /run/nscd/socket rw,
  /run/nslcd/socket rw,
  /usr/{,**/}* r,
  /{,usr/}bin/{,**/}* ixmrw,
  /{,usr/}sbin/{,**/}* ixmrw,
  /{,usr/}sbin/epi-gtk px,
  /usr/share/zero-center/zero-center.py ixmrw,
  /usr/share/zero-center/{,**/}* rwlkm,
  /usr/share/zero-center/zmds/* ixmrklw,
  /usr/{,local/}lib/python3*/dist-packages/{,**/}* mr,
  /var/{,**/}* r,
  @{HOME}/{,**/}* mrwkixl,
  }

